bundler:
  image: debian:jessie
  volumes:
    - /bundle

redis:
    image: redis
    ports:
      - "6379:6379"

web:
  build: .
  ports:
    - "4011:3000"
  volumes:
    - .:/tentacles/
  volumes_from:
    - bundler
  command: bundle exec foreman start web
