version: '3'
services:

  redis:
    image: redis
    ports:
      - "6389:6379"

  web:
    build:
      context: .
      args:
        BUNDLER_OPTS:
    ports:
      - "4011:3000"
    volumes:
      - "${PWD}:/home/tentacles/app"
    command: foreman start web
