version: '3'
services:

  redis:
    image: redis
    ports:
      - "6389:6379"

  web:
    build: .
    ports:
      - "4011:3000"
    volumes:
      - .:/home/tentacles/src/tentacles/
    command: foreman start web
